version: "3"

tasks:
  default:
    desc: Render all CV using rendercv
    deps: [setup]
    cmds:
      - rm -r rendered
      - mkdir -p rendered
      - task: render-cvs
      - find . -iname '*Van_Viet_Hieu_Anh_CV*' -delete

  setup:
    internal: true
    desc: Set up Python environment and install dependencies
    cmds:
      - python3 -m venv .venv
      - .venv/bin/pip install --upgrade pip
      - .venv/bin/pip install -r requirements.txt
    sources:
      - requirements.txt

  render-cvs:
    internal: true
    vars:
      CV:
        sh: find . -maxdepth 1 \( -name 'cv_*.yaml' -o -name 'cv_*.yml' \)

    deps:
      - for: { var: CV }
        task: render-cv
        vars:
          FILE: "{{ .ITEM }}"

  render-cv:
    internal: true
    cmds:
      - >
        .venv/bin/rendercv render {{ .FILE }}
        --design ./design.yaml
        --output-folder-name ./build
        --pdf-path ./rendered/{{ .FILE | base | trimSuffix ".yaml" | trimSuffix ".yml" }}.pdf
        -nomd -nohtml -nopng
        >> /dev/null
