name: Update CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies
        run: pip install rendercv

      - name: Update CV
        run: |
          rendercv render "cv.yaml" --output-folder-name "build"

      - name: Copy cv.pdf to root directory
        run: |
          cp ./build/Van_Viet_Hieu_Anh_CV.pdf ./cv.pdf
          cp ./build/Van_Viet_Hieu_Anh_CV.md ./README.md

          git add cv.pdf README.md
          git stash --include-untracked # Stash untracked files

      - name: Set up Git configuration
        run: |
          git config --global user.email "vanviethieuanh@gmail.com"
          git config --global user.name "vanviethieuanh"

      - name: Fetch and checkout cv branch
        run: |
          git fetch origin cv  # Fetch changes from remote cv branch
          git checkout cv       # Switch to cv branch

      - name: Rebase and apply stashed changes
        run: |
          git stash pop  # Apply the stashed changes

      - name: Commit and push changes
        run: |
          git commit -m "Update cv.pdf"
          git push origin cv  # Force push the changes to the remote cv branch
