name: Update CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies
        run: pip install rendercv

      - name: Update CV
        run: |
          rendercv render "cv.yaml" --output-folder-name "build"

      - name: Copy cv.pdf to root directory
        run: |
          cp ./build/Van_Viet_Hieu_Anh_CV.pdf ./cv.pdf
          cp ./build/Van_Viet_Hieu_Anh_CV.md ./README.md

      - name: Commit and push changes
        run: |
          git config --global user.email "vanviethieuanh@gmail.com"
          git config --global user.name "vanviethieuanh"

          git fetch origin cv  # Fetch changes from remote cv branch
          git checkout cv       # Switch to cv branch
          git reset --hard origin/cv  # Reset local branch to match remote (optional, if needed)

          # Rebase your changes on top of the remote changes
          git pull --rebase origin cv

          git add cv.pdf
          git commit -m "Update cv.pdf"

          # Force push the changes to the remote cv branch
          git push origin cv
