name: Update CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install rendercv

      - name: Update CV
        run: |
          rendercv render "cv.yaml" --output-folder-name "build"
          if [ ! -f "./build/Van_Viet_Hieu_Anh_CV.pdf" ]; then
            echo "CV file not found!"
            exit 1
          fi

      - name: Copy cv.pdf to root directory
        run: |
          cp ./build/Van_Viet_Hieu_Anh_CV.pdf ./cv.pdf
          if [ ! -f "./cv.pdf" ]; then
            echo "CV file not copied correctly!"
            exit 1
          fi

      - name: Checkout to cv branch
        uses: actions/checkout@v2
        with:
          ref: cv

      - name: Add cv.pdf
        run: |
          if [ -f "./cv.pdf" ]; then
            git add cv.pdf
          else
            echo "CV file not found in cv branch!"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git commit -m "Update cv.pdf"
          git push
